version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: claude-shop-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: claude_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: